-- TornAPIJS:player_stats:recordedAt,requestedFactionHofRank,playerId,name,level,activeStreak,ageDays,ageMonths,ageYears,hasFaction,hasCompany,factionName,factionId,companyName,companyId,hoursSinceLastAction,xanScore,averageTimeScore,combinedScore,tier,avgXanaxPerDay,avgTimePlayedHoursPerDay,allTimeXanaxTaken,xanaxTakenUntilLastMonth,xanaxTakenDuringLastMonth,allTimeEcstasyTaken,ecstasyTakenDuringLastMonth,allTimeRankedWarHits,rankedWarHitsDuringLastMonth,rankedWarsParticipatedLastMonth,timePlayed,timePlayedUntilLastMonth,timePlayedDuringLastMonth,periodUsed,xanaxMode,tornApiCallsUsed
-- TornAPIJS export
-- table: player_stats
-- columns: recordedAt, requestedFactionHofRank, playerId, name, level, activeStreak, ageDays, ageMonths, ageYears, hasFaction, hasCompany, factionName, factionId, companyName, companyId, hoursSinceLastAction, xanScore, averageTimeScore, combinedScore, tier, avgXanaxPerDay, avgTimePlayedHoursPerDay, allTimeXanaxTaken, xanaxTakenUntilLastMonth, xanaxTakenDuringLastMonth, allTimeEcstasyTaken, ecstasyTakenDuringLastMonth, allTimeRankedWarHits, rankedWarHitsDuringLastMonth, rankedWarsParticipatedLastMonth, timePlayed, timePlayedUntilLastMonth, timePlayedDuringLastMonth, periodUsed, xanaxMode, tornApiCallsUsed
INSERT INTO "player_stats" (
    "recordedAt",
    "requestedFactionHofRank",
    "playerId",
    "name",
    "level",
    "activeStreak",
    "ageDays",
    "ageMonths",
    "ageYears",
    "hasFaction",
    "hasCompany",
    "factionName",
    "factionId",
    "companyName",
    "companyId",
    "hoursSinceLastAction",
    "xanScore",
    "averageTimeScore",
    "combinedScore",
    "tier",
    "avgXanaxPerDay",
    "avgTimePlayedHoursPerDay",
    "allTimeXanaxTaken",
    "xanaxTakenUntilLastMonth",
    "xanaxTakenDuringLastMonth",
    "allTimeEcstasyTaken",
    "ecstasyTakenDuringLastMonth",
    "allTimeRankedWarHits",
    "rankedWarHitsDuringLastMonth",
    "rankedWarsParticipatedLastMonth",
    "timePlayed",
    "timePlayedUntilLastMonth",
    "timePlayedDuringLastMonth",
    "periodUsed",
    "xanaxMode",
    "tornApiCallsUsed"
)
VALUES (
    '2026-04-18T18:02:38.508Z',
    NULL,
    2163658,
    'Zurich',
    97,
    17,
    2789,
    91.63,
    7.64,
    TRUE,
    TRUE,
    'Endless Endeavor',
    14686,
    'HIRING Sandpiper Oil',
    100955,
    3.85,
    31.76,
    4.89,
    25.04,
    'F',
    0.9528,
    0.1467,
    4036,
    4007,
    29,
    16,
    0,
    725,
    0,
    0,
    5200010,
    5183932,
    16078,
    'month',
    'v2-recruitment-stats',
    65
);
